api/urls.py
from django.conf.urls import url, include
from rest_framework_swagger.views import get_swagger_view
from rest_framework_jwt.views import obtain_jwt_token

from api.views import IndexAPIView, TrendingAPIView, SearchAPIView, QuestionAPIView, QuestionAnswersAPIView, wrong_url, schema_view

urlpatterns = [
    url(regex=r"^docs/", view=schema_view),
    url(regex=r'^token-auth/', view=obtain_jwt_token),
    url(regex=r"(?P<version>(v1|v2))/index/",
        view=IndexAPIView.as_view(),
        name="index"),
    url(regex=r"^(?P<version>(v1|v2))/trending/",
        view=TrendingAPIView.as_view(),
        name="trending"),
    url(regex=r"^(?P<version>(v1|v2))/search/?$",
        view=SearchAPIView.as_view(),
        name="search"),
    url(regex=r"^(?P<version>(v1|v2))/questions/(?P<pk>[0-9]+)/answers/",
        view=QuestionAnswersAPIView.as_view(),
        name="answer"),
    url(regex=r"^(?P<version>(v1|v2))/questions/(?P<pk>[0-9]+)/",
        view=QuestionAPIView.as_view(),
        name="question"),
    url(regex=r'^', view=wrong_url),

]

hasker/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views

from user.views import SignupView, SignupDoneView, UserSettingsView
from question.models import Trend
from question.views import IndexView, AskView, QuestionView, QuestionListView, VoteView, BestAnswerView, SearchView, TagView


urlpatterns = [
    path('login/', auth_views.LoginView.as_view(
        extra_context={"trends": Trend.get_trends()}
    )),
    path('logout/', auth_views.LogoutView.as_view()),
    path('signup/', SignupView.as_view()),
    path('signup/done/', SignupDoneView.as_view()),
    path('settings/', UserSettingsView.as_view()),
    path('ask/', AskView.as_view()),
    path('question/<int:id>/', QuestionView.as_view(), name="question"),
    path('question/vote/', VoteView.as_view(), name="question_vote"),
    path('question/best/', BestAnswerView.as_view(), name="question_best"),
    path('question/list/', QuestionListView.as_view(), name="question_vote"),
    path('search/', SearchView.as_view(), name="question_search"),
    path('tag/<str:tag>/', TagView.as_view(), name="question_tag"),
    path('admin/', admin.site.urls),
    url(r'^api/', include(('api.urls', 'api'), namespace='api')),
    path('', IndexView.as_view()),
]

user/forms.py
from django import forms
from user.models import User


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email','avatar',)


class SignupForm(forms.Form):
    class Meta:
        model = User

    login = forms.CharField(label='Login', max_length=200)
    email = forms.EmailField(label='Email', max_length=200)
    password = forms.CharField(widget=forms.PasswordInput, label='Password', max_length=200)
    password2 = forms.CharField(widget=forms.PasswordInput, label='Repeat password', max_length=200)
    avatar = forms.ImageField(label='Avatar')

    def clean_login(self):
        login = self.cleaned_data['login']
        if User.objects.filter(username=login).exists():
            raise forms.ValidationError('User with login "' + login+ '" already exists')
        return login

templates/index/index.html
{% extends "base.html" %}questions_content

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/question/list.css' %}" />


    <div id="left_container" class="left w75">
        <div class="head" id="question_filter"><a class="active" data-type="date">New questions</a> | <a data-type="votes">Hot questions</a></div>
        <input type="hidden" id="page" value="{{ page }}">

        <div id="questions_content">
        {% if questions %}

            <ul id="questions_ul">
                {% for question in questions %}
                    <li class="main">
                        <ul class="list_content">
                            <li class="w10">
                                <div class="digit">{{ question.votes }}</div>
                                <div class="signa">Votes</div>
                            </li>
                            <li class="w10">
                                <div class="digit">{{ question.answers }}</div>
                                <div class="signa">Answers</div>
                            </li>
                            <li class="w60">
                                <div class="quest_cnt">
                                    <a class="head" href="/question/{{ question.id }}/">
                                        {{ question.heading }}
                                    </a>
                                    <div class="tags">
                                        {% for tag in question.tags_list %}
                                            <a href="/tag/{{ tag }}/">{{ tag }}</a>
                                        {% endfor %}
                                    </div>
                                </div>
                            </li>
                            <li class="w20">
                                <a href="/user/">{{ question.author_name }}</a>
                                <div class="sign">
                                    Added {{ question.published }} ago
                                </div>

                            </li>
                        </ul>
                    </li>
                {% endfor %}
            </ul>

            <div class="pagination">
                <span class="step-links">
                    {% if questions.has_previous %}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ questions.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ questions.number }} of {{ questions.paginator.num_pages }}
                    </span>

                    {% if questions.has_next %}
                        <a href="?page={{ questions.next_page_number }}">next</a>
                        <a href="?page={{ questions.paginator.num_pages }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>


        {% else %}
            <p>No questions are available right now.</p>
        {% endif %}

        </div>

    </div>






{% if message %}
    <p><strong>{{ message }}</strong></p>
{% endif %}


<script src="/static/js/index.js" type="text/javascript"></script>
{% endblock content %}

templates/index/settings.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index/user_settings.css' %}" />

<div id="left_container" class="left w75">
    <div id="login_container" class="">
        <h1>User settings</h1>
            <form method="post" class="common" action="/settings/" enctype="multipart/form-data">
                <div class="cont">
                    {% csrf_token %}
                    <ul class="form_ul" id="user_settings_ul">
                        <li>
                            <label>Login:</label>
                            <div class="rcon">{{ user.username }}</div>
                        </li>

                        <li>
                            <label for="id_email">Email:</label>
                            <input name="email" id="id_email" maxlength="200" required="" type="email" value="{{ user.email }}">
                        </li>
                          <li>
                            <label for="id_avatar">Avatar:</label>
                            <div class="rcon">
                                <div class="avatar_check"><input name="avatar-clear" id="avatar-clear_id" type="checkbox"><span>Clear</span></div>
                                <div class="avatar" style="background-image:url('/media/{{ user.avatar }}');background-size:cover;background-repeat:no-repeat;background-position:center center;" ></div>
                                <div class="avatar_field"><input name="avatar" id="id_avatar" accept="image/*"  type="file"></div>
                            </div>
                        </li>



                    </ul>
                    <div class="btn"><button type="submit">Save</button></div>
                </div>
            </form>
    </div>


    {% if message %}
        <p><strong>
            {{ form.errors }}
            {{ form.non_field_errors }}
            {{ message }}
        </strong></p>
    {% endif %}
</div>


{% endblock content %}

templates/index/signup.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index/signup.css' %}" />

<div id="left_container" class="left w75">
    <div id="login_container" class="">
        <h1>Sign up</h1>
            <form method="post" class="common" action="/signup/"  enctype="multipart/form-data">
                <div class="cont">
                    {% csrf_token %}
                    <ul class="form_ul">
                         {{ form.as_ul }}
                    </ul>
                    <div class="btn"><button type="submit">Enter</button></div>
                </div>
            </form>
    </div>


    {% if message %}
        <p><strong>{{ message }}</strong></p>
    {% endif %}
</div>


{% endblock content %}

templates/index/signup_done.html
{% extends "base.html" %}

{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index/signup.css' %}" />

<div id="left_container" class="left w75">
    <div id="login_container" class="">
        <h1>Sign up</h1>
        Sign Up successfully completed. You may <a href="/login/">Log In</a> now
    </div>


    {% if message %}
        <p><strong>{{ message }}</strong></p>
    {% endif %}
</div>


{% endblock content %}